=== ncbi-nlp/DeepRel/deeprel_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Dataset to train/test a CNN model",
  "title": "CNN",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "text": {
        "type": "string"
      },
      "annotations": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "Protein"
              ]
            },
            "text": {
              "type": "string"
            },
            "start": {
              "type": "number",
              "minimum": 0
            },
            "end": {
              "type": "number",
              "minimum": 0
            }
          },
          "required": ["id", "text", "start", "end", "type"]
        }
      },
      "relations": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "arg1": {
              "type": "string"
            },
            "arg2": {
              "type": "string"
            },
            "label": {
              "type": "string",
              "enum": [
                "PPI-False",
                "PPI-True"
              ]
            }
          },
          "required": ["id", "arg1", "arg2", "label"]
        }
      }
    },
    "required": [
      "id",
      "text",
      "annotations",
      "relations"
    ]
  }
}

=== ncbi-nlp/DeepRel/examples/aimed-dev.json
[
  {
    "id": "AIMed.d2.s23", 
    "text": "MAIN OUTCOME MEASURES: RBP/TTR molar ratio after 7 days hospitalisation.", 
    "annotations": [
      {
        "id": "AIMed.d2.s23.e0", 
        "type": "Protein", 
        "text": "RBP", 
        "start": 23, 
        "end": 26
      }, 
      {
        "id": "AIMed.d2.s23.e1", 
        "type": "Protein", 
        "text": "TTR", 
        "start": 27, 
        "end": 30
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d2.s23.p0", 
        "arg1": "AIMed.d2.s23.e0", 
        "arg2": "AIMed.d2.s23.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d3.s30", 
    "text": "Temporally following this growth arrest, the cells develop a senescence morphology and express senescence-associated beta-galactosidase (SA-beta-gal).", 
    "annotations": [
      {
        "id": "AIMed.d3.s30.e0", 
        "type": "Protein", 
        "text": "beta-galactosidase", 
        "start": 117, 
        "end": 135
      }, 
      {
        "id": "AIMed.d3.s30.e1", 
        "type": "Protein", 
        "text": "senescence-associated beta-galactosidase", 
        "start": 95, 
        "end": 135
      }, 
      {
        "id": "AIMed.d3.s30.e2", 
        "type": "Protein", 
        "text": "SA-beta-gal", 
        "start": 137, 
        "end": 148
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d3.s30.p0", 
        "arg1": "AIMed.d3.s30.e0", 
        "arg2": "AIMed.d3.s30.e1", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d3.s30.p1", 
        "arg1": "AIMed.d3.s30.e0", 
        "arg2": "AIMed.d3.s30.e2", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d3.s30.p2", 
        "arg1": "AIMed.d3.s30.e1", 
        "arg2": "AIMed.d3.s30.e2", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d7.s57", 
    "text": "The rates of extensive ST-3 expression and decreased E-cadherin expression were significantly higher in the de novo group (P=0.014 and 0.005, respectively).", 
    "annotations": [
      {
        "id": "AIMed.d7.s57.e0", 
        "type": "Protein", 
        "text": "ST-3", 
        "start": 23, 
        "end": 27
      }, 
      {
        "id": "AIMed.d7.s57.e1", 
        "type": "Protein", 
        "text": "E-cadherin", 
        "start": 53, 
        "end": 63
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d7.s57.p0", 
        "arg1": "AIMed.d7.s57.e0", 
        "arg2": "AIMed.d7.s57.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d14.s118", 
    "text": "Correlations between GFAp and NFL in CSF as markers for astrogliosis and neurodegeneration, and clinical and biological data were investigated.", 
    "annotations": [
      {
        "id": "AIMed.d14.s118.e0", 
        "type": "Protein", 
        "text": "GFAp", 
        "start": 21, 
        "end": 25
      }, 
      {
        "id": "AIMed.d14.s118.e1", 
        "type": "Protein", 
        "text": "NFL", 
        "start": 30, 
        "end": 33
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d14.s118.p0", 
        "arg1": "AIMed.d14.s118.e0", 
        "arg2": "AIMed.d14.s118.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d22.s181", 
    "text": "Present data concerning the renin-angiotensin system of extrarenal origin.", 
    "annotations": [
      {
        "id": "AIMed.d22.s181.e0", 
        "type": "Protein", 
        "text": "renin", 
        "start": 28, 
        "end": 33
      }, 
      {
        "id": "AIMed.d22.s181.e1", 
        "type": "Protein", 
        "text": "angiotensin", 
        "start": 34, 
        "end": 45
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d22.s181.p0", 
        "arg1": "AIMed.d22.s181.e0", 
        "arg2": "AIMed.d22.s181.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d23.s195", 
    "text": "Therefore, 1) the presence of GRs and COX-2 in nasal polyps from nonallergic patients, as well as upregulation of COX-2 expression, suggests that inflammation may play an important role in the pathophysiology of nasal polyps; and 2) glucocorticoid could be a potential treatment method for suppressing inflammatory processes.", 
    "annotations": [
      {
        "id": "AIMed.d23.s195.e0", 
        "type": "Protein", 
        "text": "COX-2", 
        "start": 38, 
        "end": 43
      }, 
      {
        "id": "AIMed.d23.s195.e1", 
        "type": "Protein", 
        "text": "COX-2", 
        "start": 114, 
        "end": 119
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d23.s195.p0", 
        "arg1": "AIMed.d23.s195.e0", 
        "arg2": "AIMed.d23.s195.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d26.s215", 
    "text": "Granulysin has been identified as an effector molecule co-localized with perforin in the cytotoxic granules of cytotoxic T lymphocytes and natural killer (NK) cells, and has been reported to kill intracellular pathogens in infected cells in the presence of perforin and to induce a cytotoxic effect against tumor cells.", 
    "annotations": [
      {
        "id": "AIMed.d26.s215.e0", 
        "type": "Protein", 
        "text": "Granulysin", 
        "start": 0, 
        "end": 10
      }, 
      {
        "id": "AIMed.d26.s215.e1", 
        "type": "Protein", 
        "text": "perforin", 
        "start": 73, 
        "end": 81
      }, 
      {
        "id": "AIMed.d26.s215.e2", 
        "type": "Protein", 
        "text": "perforin", 
        "start": 257, 
        "end": 265
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d26.s215.p0", 
        "arg1": "AIMed.d26.s215.e0", 
        "arg2": "AIMed.d26.s215.e1", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d26.s215.p1", 
        "arg1": "AIMed.d26.s215.e0", 
        "arg2": "AIMed.d26.s215.e2", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d26.s215.p2", 
        "arg1": "AIMed.d26.s215.e1", 
        "arg2": "AIMed.d26.s215.e2", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d28.s235", 
    "text": "The hGITRL gene mapped to chromosome 1q23, near the gene for the TNF homolog Fas/CD95 ligand [5].", 
    "annotations": [
      {
        "id": "AIMed.d28.s235.e0", 
        "type": "Protein", 
        "text": "hGITRL", 
        "start": 4, 
        "end": 10
      }, 
      {
        "id": "AIMed.d28.s235.e1", 
        "type": "Protein", 
        "text": "Fas", 
        "start": 77, 
        "end": 80
      }, 
      {
        "id": "AIMed.d28.s235.e2", 
        "type": "Protein", 
        "text": "CD95 ligand", 
        "start": 81, 
        "end": 92
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d28.s235.p0", 
        "arg1": "AIMed.d28.s235.e0", 
        "arg2": "AIMed.d28.s235.e1", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d28.s235.p1", 
        "arg1": "AIMed.d28.s235.e0", 
        "arg2": "AIMed.d28.s235.e2", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d28.s235.p2", 
        "arg1": "AIMed.d28.s235.e1", 
        "arg2": "AIMed.d28.s235.e2", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d29.s245", 
    "text": "These Ala mutants triggered neutrophil degranulation and induced calcium responses mediated by CXCR1 and CXCR2.", 
    "annotations": [
      {
        "id": "AIMed.d29.s245.e0", 
        "type": "Protein", 
        "text": "CXCR1", 
        "start": 95, 
        "end": 100
      }, 
      {
        "id": "AIMed.d29.s245.e1", 
        "type": "Protein", 
        "text": "CXCR2", 
        "start": 105, 
        "end": 110
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d29.s245.p0", 
        "arg1": "AIMed.d29.s245.e0", 
        "arg2": "AIMed.d29.s245.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d30.s253", 
    "text": "These results suggest that PS1 and PS2 partly differ in function.", 
    "annotations": [
      {
        "id": "AIMed.d30.s253.e0", 
        "type": "Protein", 
        "text": "PS1", 
        "start": 27, 
        "end": 30
      }, 
      {
        "id": "AIMed.d30.s253.e1", 
        "type": "Protein", 
        "text": "PS2", 
        "start": 35, 
        "end": 38
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d30.s253.p0", 
        "arg1": "AIMed.d30.s253.e0", 
        "arg2": "AIMed.d30.s253.e1", 
        "label": "PPI-False"
      }
    ]
  }, 
  {
    "id": "AIMed.d32.s273", 
    "text": "Our results indicate that Phe93 and Phe205 are important for both EPO and EMP1 binding, Met150 is not important for EPO binding but is critical for EMP1 binding, and Thr151 is not important for binding either ligand.", 
    "annotations": [
      {
        "id": "AIMed.d32.s273.e0", 
        "type": "Protein", 
        "text": "EPO", 
        "start": 66, 
        "end": 69
      }, 
      {
        "id": "AIMed.d32.s273.e1", 
        "type": "Protein", 
        "text": "EMP1", 
        "start": 74, 
        "end": 78
      }, 
      {
        "id": "AIMed.d32.s273.e2", 
        "type": "Protein", 
        "text": "EPO", 
        "start": 116, 
        "end": 119
      }, 
      {
        "id": "AIMed.d32.s273.e3", 
        "type": "Protein", 
        "text": "EMP1", 
        "start": 148, 
        "end": 152
      }
    ], 
    "relations": [
      {
        "id": "AIMed.d32.s273.p0", 
        "arg1": "AIMed.d32.s273.e0", 
        "arg2": "AIMed.d32.s273.e1", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d32.s273.p1", 
        "arg1": "AIMed.d32.s273.e0", 
        "arg2": "AIMed.d32.s273.e2", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d32.s273.p2", 
        "arg1": "AIMed.d32.s273.e0", 
        "arg2": "AIMed.d32.s273.e3", 
        "label": "PPI-False"
      }, 
      {
        "id": "AIMed.d32.s273.p3",
